sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    (cargo install rustfmt || true) &&
    export PATH=$HOME/.local/bin:$PATH &&
    export PATH=$HOME/.cargo/bin:$PATH

script:
  - |
    cargo fmt -- --write-mode=diff &&
    travis-cargo build &&
    travis-cargo test

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success:
  - travis-cargo --only stable coveralls --no-sudo --exclude-pattern="src/main.rs,src/new.rs,target/debug/build/"

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="clippy"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
